### ISSUE TITLE
ExpatError parseString parser.Parse(string, True)

### ISSUE THREAD

**Issue by helmus** [onelogin/python-saml#208]
We are seeing this error happening in our system, any guess what it is? 
```
Traceback (most recent call last):
File "/opt/foo/app/virtualenv/application-web/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/foo/application-web/foo/foo/apps/account/saml_sso.py", line 728, in saml_metadata metadata = saml_settings.get_sp_metadata()
File "/opt/foo/app/virtualenv/application-web/lib/python2.7/site-packages/onelogin/saml2/settings.py", line 682, in get_sp_metadata metadata = OneLogin_Saml2_Metadata.sign_metadata(metadata, key_metadata, cert_metadata, signature_algorithm, digest_algorithm)
File "/opt/foo/app/virtualenv/application-web/lib/python2.7/site-packages/onelogin/saml2/metadata.py", line 227, in sign_metadata return OneLogin_Saml2_Utils.add_sign(metadata, key, cert, False, sign_algorithm, digest_algorithm)
File "/opt/foo/app/virtualenv/application-web/lib/python2.7/site-packages/onelogin/saml2/utils.py", line 900, in add_sign newdoc = parseString(tostring(elem, encoding='unicode').encode('utf-8'))
File "/opt/foo/app/virtualenv/application-web/lib/python2.7/site-packages/defusedxml/minidom.py", line 35, in parseString forbid_external=forbid_external)
File "/opt/foo/app/virtualenv/application-web/lib/python2.7/site-packages/defusedxml/expatbuilder.py", line 110, in parseString return builder.parseString(string)
File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString parser.Parse(string, True)
ExpatError: no element found: line 1, column 0
```

**Comment by pitbulk** [comment]
Never saw it before...but it seems that the metadata string provided is not an XML.. can you try to get it and validate with any XML online tool validator?

**Comment by pitbulk** [comment]
any progress?

**Comment by helmus** [comment]
Hey Man, thanks for following up. It turned out this was a side effect of installing the uwsgi datadog collector. We where unable to determine the exact cause tough. 
https://github.com/DataDog/uwsgi-dogstatsd
