### ISSUE TITLE
run demo-django got segmentation fault

### ISSUE THREAD

**Issue by tangyin** [onelogin/python-saml#217]
OS: centos 7.2
pip freeze:
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
chardet==2.2.1
configobj==4.7.2
decorator==3.4.0
defusedxml==0.4.1
Django==1.8
dm.xmlsec.binding==1.3.3
enum34==1.1.6
iniparse==0.4
ipython==5.2.0
ipython-genutils==0.2.0
isodate==0.6.0
kitchen==1.1.1
langtable==0.0.31
lxml==4.1.1
M2Crypto==0.21.1
pathlib2==2.3.0
perf==0.1
pexpect==4.3.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pycurl==7.19.0
Pygments==2.2.0
pygobject==3.14.0
pygpgme==0.3
pyliblzma==0.5.3
pyparsing==1.5.6
python-augeas==0.5.0
python-dmidecode==3.10.13
python-saml==2.3.0
pyudev==0.15
pyxattr==0.5.1
scandir==1.6
simplegeneric==0.8.1
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
traitlets==4.3.2
urlgrabber==3.10
wcwidth==0.1.7
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4

when I runserver in demo-django and visit the index url, the console return a segmentation fault.
/var/log/message: localhost kernel: python[11471]: segfault at 10 ip 00007f841b9dad12 sp 00007f842989e4a0 error 4 in etree.so[7f841b8d0000+4e5000]

Any help? thanks a lot!

**Comment by pitbulk** [comment]
try installing the python-saml repo and then run the test
```
python setup.py test
```
and see if it work or not.

**Comment by tangyin** [comment]
Run the test and got an Error:

`python setup.py test
running test
running egg_info
writing requirements to src/python_saml.egg-info/requires.txt
writing src/python_saml.egg-info/PKG-INFO
writing top-level names to src/python_saml.egg-info/top_level.txt
writing dependency_links to src/python_saml.egg-info/dependency_links.txt
reading manifest file 'src/python_saml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'src/python_saml.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    keywords='saml saml2 xmlsec django flask',
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'idp_metadata_parser_test'`
